name: nvchecker

on:
  push:
  workflow_dispatch:

jobs:
  nvcmp:
    runs-on: ubuntu-latest
    outputs:
      mymatrix: ${{ steps.nvcmp.outputs.myoutput }}

    steps:
    - name: checkout
      uses: actions/checkout@v4

    - name: nvcmp
      id: nvcmp
      run: |
        echo "myoutput=$(cat ./nvcmp.json)" >> $GITHUB_OUTPUT
        echo ${{ steps.nvcmp.outputs.myoutput }}

  run-matrix:
    needs: nvcmp
    runs-on: ubuntu-latest
    steps:
    - name: run
      run: |
        echo ${{ fromJson(needs.nvcmp.outputs.mymatrix) }}
        echo ${{ needs.nvcmp.outputs.mymatrix }}


