name: nvchecker

on:
  push:
  workflow_dispatch:

jobs:
  nvcmp:
    runs-on: ubuntu-latest
    outputs:
      nvcmp: ${{ steps.nvchecker.outputs.nvcmp }}

    steps:
    - name: checkout
      uses: actions/checkout@v4

    - name: nvcmp
      id: nvchecker
      run: |
        pip install nvchecker
        echo "nvcmp=$(nvcmp --file overlay.toml --json --newer | jq 'map({name, newver, oldver, delta})' | jq -c .)" >> $GITHUB_OUTPUT

  run-matrix:
    needs: nvcmp
    runs-on: ubuntu-latest
    strategy:
      matrix:
        include: ${{ fromJson(needs.nvcmp.outputs.nvcmp) }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Process package
        env:
          name: ${{ matrix.name }}
          newver: ${{ matrix.newver }}
          oldver: ${{ matrix.oldver }}
          delta: ${{ matrix.delta }}
        run: |
          echo "Processing package $name"

