name: nvchecker

on:
  push:
  workflow_dispatch:

jobs:
  nvcmp:
    runs-on: ubuntu-latest
    outputs:
      nvcmp: ${{ steps.nvchecker.outputs.nvcmp }}

    steps:
    - name: checkout
      uses: actions/checkout@v4

    - name: nvcmp
      id: nvchecker
      run: |
        pip install nvchecker
        echo "nvcmp=$(nvcmp --file overlay.toml --json --newer)" >> $GITHUB_OUTPUT
        echo ${{ steps.nvcmp.outputs.myoutput }}

  run-matrix:
    needs: nvcmp
    runs-on: ubuntu-latest
    strategy:
      matrix:
        include: [
          {
            "package": "app-editors/cursor",
            "newver": "7.36.11",
            "oldver": null,
            "delta": "added"
          },
          {
            "package": "x11-wm/hypr",
            "newver": "1.1.4",
            "oldver": null,
            "delta": "added"
          }
        ]
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Process package
        run: |
          echo "Processing package ${{ matrix.package }}"
          echo "New version: ${{ matrix.newver }}"
          echo "Old version: ${{ matrix.oldver }}"
          echo "Delta: ${{ matrix.delta }}"


